FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow==2.13.0 \
    scikit-learn==1.7.1 \
    pandas==2.3.3 \
    numpy==2.2.6

COPY ml/train.py .

CMD ["python", "train.py"]