FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow==2.13.0 \
    scikit-learn==1.5.0 \
    pandas==2.2.2 \
    numpy==1.26.4

COPY ml/train.py .

CMD ["python", "train.py"]